### ISSUE TITLE
Button's font property does not work

### ISSUE THREAD

**Issue by laurenrad** [c-jo/riscos-toolbox#26]
The getter and setter for the Button class's font property do not work; on the setter side, the setter is misspelled as "fond" rather than "font". However, additionally there is as far as I'm aware no GetFont method in the Button object, so the property getter won't work. 
I have a patch downstream which removes these and replaces them with a set_font method which I can open a PR for.

**Comment by laurenrad** [comment]
Something I've realised though while testing some other things is the other gadgets I checked in have different behaviour in that they don't scale the width and height values, as this one does, which I carried over from what was already there. I will leave it up to the maintainer on this one to make the call on how to handle this, but heads up.

**Comment by c-jo** [comment]
https://gitlab.riscosopen.org/RiscOS/Sources/Toolbox/tboxlib/-/blob/master/objects/h/window#L790

Would indicate there is a way to get the font, although I've not checked the gadget code itself.

**Comment by laurenrad** [comment]
Adding this comment because I realized we had this discussion by email after 29 Sep, but it was never put on record here. After further review, there is evidence in the Toolbox code of a method to get the font, but it was never implemented.

**Comment by c-jo** [comment]
I'm closing this as I think it's been covered by the miscop review PR. The upshot of which is there a method there to set the font and it's size.
