### ISSUE TITLE
Typo in DataTransferMessage

### ISSUE THREAD

**Issue by mephillips-durham** [c-jo/riscos-toolbox#4]
There appears to be a typo in the name of the destination icon field in the DataTransferMessage class:

https://github.com/c-jo/riscos-toolbox/blob/a3a2dff19e7c3d429d1a3f34d4ff441daa8d5a52/riscos_toolbox/user_messages/data_transfer.py#L19

This class probably should not have the "k" in the name:

https://github.com/c-jo/riscos-toolbox/blob/a3a2dff19e7c3d429d1a3f34d4ff441daa8d5a52/riscos_toolbox/user_messages/data_transfer.py#L37

Also in the DataOpenMessage there is a field called pposition. Should that be simply position?

https://github.com/c-jo/riscos-toolbox/blob/a3a2dff19e7c3d429d1a3f34d4ff441daa8d5a52/riscos_toolbox/user_messages/data_transfer.py#L46

**Comment by c-jo** [comment]
Thanks!
