### ISSUE TITLE
Signed/Unsigned mixup when getting LicenceType from ProgInfo

### ISSUE THREAD

**Issue by laurenrad** [c-jo/riscos-toolbox#70]
https://github.com/c-jo/riscos-toolbox/blob/c5adb23c93c764343f477eac575e057faee0fd74/riscos_toolbox/objects/proginfo.py#L46

Here in proginfo.py, the accessor for the licence_type property calls self._miscop_get_unsigned to get the licence type. However, this is a signed value according to Toolbox documentation and it indeed does seem to matter, as during testing this resulted in an error that an extremely large number was not a valid member of the LicenceType enum. (While not explicitly stated in the manual, it appears that if this field is disabled altogether, the Toolbox returns -1 here.)

This call should be changed to use self.miscop_get_signed instead.

**Comment by c-jo** [comment]
Although -1 would still not cast to the enum. Perhaps in this case we should return None?

**Comment by laurenrad** [comment]
Ah, you caught me just as I submitted the PR. I added an extra value to the enum for Unset; returning None also seems like a valid enough option, so I'll let you make the call on that.

**Comment by c-jo** [comment]
I've merged in the PR, but I think on balance it's clearer to return None if there licence type isn't there. Mainly because adding "Unset" to the enum gives the impression you can set the license type to Unset, and I'm not sure that makes sense, so I changed that bit.
   
  
    
   
  
    
   
  
    
   
   
   
    On 20/11/2023 09:48 GMT Lauren Rad ***@***.***> wrote:
    
   
     
    
   
     
    
   
    Ah, you caught me just as I submitted the PR. I added an extra value to the enum for Unset; returning None also seems like a valid enough option, so I'll let you make the call on that.
