### ISSUE TITLE
Getting state of a ScrollList does not work.

### ISSUE THREAD

**Issue by laurenrad** [c-jo/riscos-toolbox#9]
In the ScrollList class, there is an error in this SWI call's argument format string:
```
    @property
    def state(self):
        return swi.swi("Toolbox_ObjectMiscOp","0II;I",
                       self.window.id, 16410, self.id)
```
The missing int argument here results in an Invalid Component ID error being thrown.

If changed to this:
```
    @property
    def state(self):
        return swi.swi("Toolbox_ObjectMiscOp","0iii;I",
                       self.window.id, 16410, self.id)
```

Getting the state works properly.

Also note ComponentId and ObjectId are both typedefs for signed int, so these were changed to lowercase i as I believe that uppercase I is unsigned?

**Comment by c-jo** [comment]
Yes, it should. I think there are a few cases of this being wrong. I think it should actually be "iIi" (window and component IDs are signed, the MiscOp code is unsigned although in practice it doesn't matter).

**Comment by c-jo** [comment]
the set state function has a similar bug I believe.
