### ISSUE TITLE
object deletion broken

### ISSUE THREAD

**Issue by laurenrad** [c-jo/riscos-toolbox#90]
https://github.com/c-jo/riscos-toolbox/blob/9a7c5ef61475e3a809b9bf0e48f71e0731cfe6d4/riscos_toolbox/base.py#L36

When this was changed to take an object rather than an ID, code was added to remove it from _objects as well; however, this tries to use "id" as a key, which doesn't exist; this should be "object.id".

**Comment by c-jo** [comment]
Perhaps the method should take either?

**Comment by laurenrad** [comment]
It possibly could, but It was new in the most recent version anyway and therefore only set up to take an ID very briefly (my design, I take the blame) so personally I think just having it pass the object is better; if you have a Toolbox object that exists outside of the library, you can call the Toolbox directly and the library should have never been the wiser. This breakage is just a side effect of the change though, not a consequence, so it can be fixed without a change to the design as it currently stands.
